<?php
header('Content-Type: text/html; charset=utf-8');

// Thinking steps data
$thinkingSteps = [
    'Extracting core skills',
    'Mapping target locations', 
    'Identifying ideal companies',
    'Finding equivalent job titles',
    'Building search'
];

// System commands
$commands = [
    'render' => 'appear',
    'nextAction' => 'proceed-after-render',
    'thinkingSteps' => $thinkingSteps
];

// Output the content
?>
<div class="thinking-steps" id="thinking-steps">
    <!-- Steps will be dynamically generated by JavaScript -->
</div>
<script type="application/json" id="system-commands">
<?php echo json_encode($commands); ?>
</script>
